import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADIUS, SHADOWS } from '../../../components/constants/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    height: 56,
    backgroundColor: COLORS.backgroundWhite,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderGray,
    position: 'relative',
  },
  headerIconLeft: {
    position: 'absolute',
    left: 12,
    width: 32,
    alignItems: 'flex-start',
  },
  headerIconRight: {
    position: 'absolute',
    right: 12,
    width: 32,
    alignItems: 'flex-end',
  },
  headerTitle: {
    fontSize: FONTS.large,
    fontWeight: '700',
    color: COLORS.textBlack,
    textAlign: 'center',
  },
  scrollView: { flex: 1 },
  scrollContent: { padding: 12, paddingBottom: 24 },
  card: {
    backgroundColor: COLORS.backgroundWhite,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderGray,
    padding: 12,
    marginBottom: 12,
  },
  companyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  companyAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.secondary,
    marginRight: 12,
  },
  companyTextWrap: { flex: 1 },
  companyTitle: {
    fontSize: FONTS.small,
    color: COLORS.textGray,
    marginBottom: 2,
  },
  companySubtitle: {
    fontSize: FONTS.regular,
    color: COLORS.textBlack,
    fontWeight: '600',
  },
  planChip: {
    backgroundColor: COLORS.secondary,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  planChipText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  planLines: { marginTop: 8, marginBottom: 8 },
  planLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  planLineLabel: {
    fontSize: FONTS.small,
    color: COLORS.textGray,
  },
  planLineValue: {
    fontSize: FONTS.small,
    color: COLORS.textBlack,
    fontWeight: '600',
  },
  planActive: {
    fontSize: FONTS.small,
    color: COLORS.primary,
    fontWeight: '700',
  },
  planActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  btnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.borderGray,
    backgroundColor: COLORS.backgroundWhite,
    flex: 1,
    marginRight: 8,
  },
  btnOutlineText: {
    fontSize: FONTS.small,
    color: COLORS.textBlack,
    fontWeight: '600',
  },
  btnPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.primary,
    flex: 1,
    marginLeft: 8,
  },
  btnPrimaryText: {
    fontSize: FONTS.small,
    color: COLORS.textWhite,
    fontWeight: '700',
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: COLORS.backgroundWhite,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.borderGray,
    padding: 12,
    ...SHADOWS.light,
  },
  metricIconWrap: { position: 'absolute', right: 10, top: 10, opacity: 0.6 },
  metricTitle: { fontSize: FONTS.small, color: COLORS.textGray, marginBottom: 4 },
  metricNumber: { fontSize: 26, fontWeight: '700', color: COLORS.textBlack, marginBottom: 2 },
  metricSub: { fontSize: FONTS.small, color: COLORS.textGray },
  sectionTitle: {
    fontSize: FONTS.regular,
    color: COLORS.textBlack,
    fontWeight: '700',
    marginBottom: 8,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderGray,
  },
  listItemText: {
    flex: 1,
    marginLeft: 10,
    fontSize: FONTS.small,
    color: COLORS.textBlack,
  },
});
